### PR TITLE
Shortens Benediction quest giver respawn timer to 10 minutes.

### PR DESCRIPTION
**Pull request by rickharrison**
As Elysium population grows, so does the pain associated with certain aspects of vanilla WoW. One example of this is black lotus and other herbs, which Elysium staff has graciously lowered the respawn timer to help alleviate the population issues.

In my guilds (Rise) opinion, the priest Benediction quest line is surrounded with toxicity, griefing, and frustration which takes away from the "epic" feel of the quest. There are consistently 10-12 people in a line regardless of time of day. Some people aren't civil and either troll, or bypass the line, which leaves everyone else with the rug swept out from under them.  The population is too large for a two hour NPC reset.

Please consider accepting this PR and reducing the respawn timer of Eris Havenfire

### CODE REVIEW

**Comment by brotalnia** [comment]
She seems to have a different respawn time in every project's database.

Elysium - 7200
cMaNGOS - 600
MangosZero - 345
TrinityCore - 300

**Comment by rickharrison** [comment]
Those all seem like much more reasonable values than the current one Elysium has.

**Comment by brotalnia** [comment]
Yeah but which one is the correct one :D

**Comment by thepparker** [comment]
No change to the spawn will be made at this time

**Pull request closed without merging**
